---
- name: Install dependencies
  community.general.pkgng:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx
    - wget

- name: Create www directory
  ansible.builtin.file:
    path: /var/www
    state: directory
    owner: root
    group: nogroup
    mode: '0755'

- name: Copy nginx config
  ansible.builtin.copy:
    src: nginx.conf
    dest: /usr/local/etc/nginx/nginx.conf
    owner: root
    group: wheel
    mode: "0644"

- name: Copy deploy script
  ansible.builtin.copy:
    src: deploy_totp_tor.sh
    dest: /usr/local/bin/deploy_totp_tor.sh
    owner: root
    group: wheel
    mode: "0755"

- name: Run deploy script # yamllint disable rule:command-instead-of-shell
  ansible.builtin.shell:
    cmd: /usr/local/bin/deploy_totp_tor.sh
    creates: /var/www/index.html

- name: Enable nginx on boot
  community.general.sysrc:
    name: nginx_enable
    value: "YES"

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Configure newsyslog
  ansible.builtin.copy:
    src: newsyslog.conf
    dest: /etc/newsyslog.conf.d/nginx.conf
    owner: root
    group: wheel
    mode: "0644"
